os: linux
dist: xenial
language: python
python:
  - 3.8
  - 3.9
# command to run tests
before_install:
  - pip install --upgrade pip setuptools wheel pytest codecov
  - sudo apt-get -y install swig
install:
  - pip install -e .[test]
script: 
  - pytest
after_success:
  - codecov
