name: Test

on:
  push:
    branches:
      - $default-branch
  pull_request:
    paths:
      - "ai_traineree/**.py"

jobs:
  build-n-test:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Latest on 2024-12-24
          version: "0.5.11"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          # Using pinned version
          # TODO: Do matrix for supported versions
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest
