name: Linter

on: [ push ]

jobs:
  build-n-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install test dependencies
        run: |
          pip install -e .[dev]
      - name: Run ISort check
        run: python -m isort --check .
      - name: Run Black check
        run: python -m black --check .
      - name: Run PyCodeStyle check
        run: python -m pycodestyle .
