name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with: # Latest on 2024-12-28
          version: "0.5.13"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Build package
        run: uv build
        
      - name: Publish package
        run: uv publish
